language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.8.0
  - DJANGO_VERSION=1.9.0
install:
  - pip install -q Django~=$DJANGO_VERSION --use-mirrors
  - pip install -r requirements_test.txt
script: ./run_tests.py
